[[odrpack]]
arch = "aarch64"
git-tree-sha1 = "e737776fde2198cdb23848f5315c0a22a3d49ee2"
libgfortran_version = "5.0.0"
os = "macos"

    [[odrpack.download]]
    sha256 = "a640d6fbdbf4cec50919496d362a7f8d1e13a4507347cf4d4e9c6f93350482ce"
    url = "https://github.com/JuliaBinaryWrappers/odrpack_jll.jl/releases/download/odrpack-v3.0.1+0/odrpack.v3.0.1.aarch64-apple-darwin-libgfortran5.tar.gz"
[[odrpack]]
arch = "aarch64"
git-tree-sha1 = "9d31d1d9f4189619f680aa2d52383bd4a6da0996"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[odrpack.download]]
    sha256 = "4670150c2ca825a5bf15f2e8833683ad126da49307a568dad27d401c7a42fef9"
    url = "https://github.com/JuliaBinaryWrappers/odrpack_jll.jl/releases/download/odrpack-v3.0.1+0/odrpack.v3.0.1.aarch64-linux-gnu-libgfortran5.tar.gz"
[[odrpack]]
arch = "aarch64"
git-tree-sha1 = "1344a23f2be66316a5d7462dd2e63b8d37daa62a"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[odrpack.download]]
    sha256 = "b67d4d0cc6e97b4fdd581641f6762780e9db8d58692365f6a11f79c6a0c31242"
    url = "https://github.com/JuliaBinaryWrappers/odrpack_jll.jl/releases/download/odrpack-v3.0.1+0/odrpack.v3.0.1.aarch64-linux-musl-libgfortran5.tar.gz"
[[odrpack]]
arch = "aarch64"
git-tree-sha1 = "304ff594c7612cf83411bf810185973ddbdeee45"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[odrpack.download]]
    sha256 = "32774d3e71b969202a1ce7cf0fb51ebf48a69a0dfce2a31064a28086a7dea4c6"
    url = "https://github.com/JuliaBinaryWrappers/odrpack_jll.jl/releases/download/odrpack-v3.0.1+0/odrpack.v3.0.1.aarch64-unknown-freebsd-libgfortran5.tar.gz"
[[odrpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5a6f3aed7d8cbfb36d0709a6f13a70a0d50a2ce8"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[odrpack.download]]
    sha256 = "542121495a60077f2d2eb3a87fdaa99874789a058ec1bc67e5d9ee56387f88c9"
    url = "https://github.com/JuliaBinaryWrappers/odrpack_jll.jl/releases/download/odrpack-v3.0.1+0/odrpack.v3.0.1.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[odrpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "20c04722af4e880024980224a82a7a1c26160951"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[odrpack.download]]
    sha256 = "5ffae4e1e136dd74d5c6f8da9aaafc7763047f67841764a52c6c59791dba624c"
    url = "https://github.com/JuliaBinaryWrappers/odrpack_jll.jl/releases/download/odrpack-v3.0.1+0/odrpack.v3.0.1.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[odrpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8b30ca847afef2bd211dc32689c6333a93945ae6"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[odrpack.download]]
    sha256 = "bb212ab3cd9e823fb3464e6664781e8d1a97403fb007c30e11a66d20a2f2a2b6"
    url = "https://github.com/JuliaBinaryWrappers/odrpack_jll.jl/releases/download/odrpack-v3.0.1+0/odrpack.v3.0.1.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[odrpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "73e6c79f4b49afcabf86b53d6cc0231bbaf5b711"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[odrpack.download]]
    sha256 = "2ec7b32e2c9d3a0515f5f2760bfdef6e16f1e3e4fde4ef2a7944a63041c6f068"
    url = "https://github.com/JuliaBinaryWrappers/odrpack_jll.jl/releases/download/odrpack-v3.0.1+0/odrpack.v3.0.1.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[odrpack]]
arch = "i686"
git-tree-sha1 = "c8e17c2e7fe1139f50bdcbbabea532f7f32ee98c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[odrpack.download]]
    sha256 = "f7a5d2bf1c45d02e62df95ac241cd793b13bf5c0d35f3ae21cdcf254544e99c6"
    url = "https://github.com/JuliaBinaryWrappers/odrpack_jll.jl/releases/download/odrpack-v3.0.1+0/odrpack.v3.0.1.i686-linux-gnu-libgfortran5.tar.gz"
[[odrpack]]
arch = "i686"
git-tree-sha1 = "f3afff6a5b98257b18eac63b4aa02e512ad31b60"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[odrpack.download]]
    sha256 = "2ef0dd70ed677d82210f37d2d4dfee5bce43cde876bdc1a232237a728a0d0f02"
    url = "https://github.com/JuliaBinaryWrappers/odrpack_jll.jl/releases/download/odrpack-v3.0.1+0/odrpack.v3.0.1.i686-linux-musl-libgfortran5.tar.gz"
[[odrpack]]
arch = "i686"
git-tree-sha1 = "6e7139ec5904c721eda357fa70681fb489f74a32"
libgfortran_version = "5.0.0"
os = "windows"

    [[odrpack.download]]
    sha256 = "a24ff0567fbd597e6b7365ae89852ad3d29ac3a56f37ec448f2eca6a4c094276"
    url = "https://github.com/JuliaBinaryWrappers/odrpack_jll.jl/releases/download/odrpack-v3.0.1+0/odrpack.v3.0.1.i686-w64-mingw32-libgfortran5.tar.gz"
[[odrpack]]
arch = "powerpc64le"
git-tree-sha1 = "b2f882a2d96f09e76c166e9af110943e0dbe67b5"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[odrpack.download]]
    sha256 = "5f88a351ed266d25f7042d7657d146a3348f3511096949e4a47c26218fafb685"
    url = "https://github.com/JuliaBinaryWrappers/odrpack_jll.jl/releases/download/odrpack-v3.0.1+0/odrpack.v3.0.1.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[odrpack]]
arch = "riscv64"
git-tree-sha1 = "0b5a3a1aee7e9323ff51426303a1042332ce7b65"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[odrpack.download]]
    sha256 = "fee65531d04c732bd3ca776ee20bcd37130c23b5c5f7bdff168dd6ebc514c30f"
    url = "https://github.com/JuliaBinaryWrappers/odrpack_jll.jl/releases/download/odrpack-v3.0.1+0/odrpack.v3.0.1.riscv64-linux-gnu-libgfortran5.tar.gz"
[[odrpack]]
arch = "x86_64"
git-tree-sha1 = "eb28711a76836c84e87bf8c77e32f8f52eb0ae4c"
libgfortran_version = "5.0.0"
os = "macos"

    [[odrpack.download]]
    sha256 = "b88c2a436d004177581568119e084b516b67e415fa5016d9058cb46903faa0a1"
    url = "https://github.com/JuliaBinaryWrappers/odrpack_jll.jl/releases/download/odrpack-v3.0.1+0/odrpack.v3.0.1.x86_64-apple-darwin-libgfortran5.tar.gz"
[[odrpack]]
arch = "x86_64"
git-tree-sha1 = "c76006f0867d6b83072b9a76f04ab79cccb20bad"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[odrpack.download]]
    sha256 = "509de4e85cf9e9febfa67dbcb7cc000f8db92366909b9d71a3fa505d981a5c07"
    url = "https://github.com/JuliaBinaryWrappers/odrpack_jll.jl/releases/download/odrpack-v3.0.1+0/odrpack.v3.0.1.x86_64-linux-gnu-libgfortran5.tar.gz"
[[odrpack]]
arch = "x86_64"
git-tree-sha1 = "72da4c85e629d1cc4645e38237bf551ab0ead198"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[odrpack.download]]
    sha256 = "2da7ddc96069877a9ac3cd4f6264488edc6050f3fd6664ba642595b2ba67f84c"
    url = "https://github.com/JuliaBinaryWrappers/odrpack_jll.jl/releases/download/odrpack-v3.0.1+0/odrpack.v3.0.1.x86_64-linux-musl-libgfortran5.tar.gz"
[[odrpack]]
arch = "x86_64"
git-tree-sha1 = "294c4566cf572fad49e13f9f251e81ee02744256"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[odrpack.download]]
    sha256 = "6e8279f3407f30921e40e90433d6cfa51438b7455cf9dccd5ec63c73faff2971"
    url = "https://github.com/JuliaBinaryWrappers/odrpack_jll.jl/releases/download/odrpack-v3.0.1+0/odrpack.v3.0.1.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[odrpack]]
arch = "x86_64"
git-tree-sha1 = "1939774f2e9a2abe37837fa4d1a11c7c36dca9f2"
libgfortran_version = "5.0.0"
os = "windows"

    [[odrpack.download]]
    sha256 = "3f096d5227221ebd9adc12747fde53a72c4abb81b4aac7d109b28edabd8d7372"
    url = "https://github.com/JuliaBinaryWrappers/odrpack_jll.jl/releases/download/odrpack-v3.0.1+0/odrpack.v3.0.1.x86_64-w64-mingw32-libgfortran5.tar.gz"
