[[odrpack]]
arch = "aarch64"
git-tree-sha1 = "0476f5dad2d9c9db565c042197597924dac254af"
libgfortran_version = "5.0.0"
os = "macos"

    [[odrpack.download]]
    sha256 = "8e3c82b4a54dd67603dedf623a0e2aefade71a3b212036e44b136da054fbbcc7"
    url = "https://github.com/JuliaBinaryWrappers/odrpack_jll.jl/releases/download/odrpack-v2.0.3+0/odrpack.v2.0.3.aarch64-apple-darwin-libgfortran5.tar.gz"
[[odrpack]]
arch = "aarch64"
git-tree-sha1 = "ae2861feee222d823a48087786aef40595d1698a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[odrpack.download]]
    sha256 = "d88e998726c5ca18c2f5984bba32cb270c01bd4000450a84c2e4cecbda5f40f7"
    url = "https://github.com/JuliaBinaryWrappers/odrpack_jll.jl/releases/download/odrpack-v2.0.3+0/odrpack.v2.0.3.aarch64-linux-gnu-libgfortran5.tar.gz"
[[odrpack]]
arch = "aarch64"
git-tree-sha1 = "d6d1c017e645bfff7856b612b791dfe67461e271"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[odrpack.download]]
    sha256 = "8cd1ca1c6dc22331acf32e6fb75800338cf36f2241e1dd7bd6a4349195f1b2a2"
    url = "https://github.com/JuliaBinaryWrappers/odrpack_jll.jl/releases/download/odrpack-v2.0.3+0/odrpack.v2.0.3.aarch64-unknown-freebsd-libgfortran5.tar.gz"
[[odrpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0ca981420f026dccc73975cd9ea8b0e8f9aa82c5"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[odrpack.download]]
    sha256 = "a7d53f21ef9cd61a0a1b0918c6244135e37697030df53ed039cf8e21ff3fcb0b"
    url = "https://github.com/JuliaBinaryWrappers/odrpack_jll.jl/releases/download/odrpack-v2.0.3+0/odrpack.v2.0.3.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[odrpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d56a0b10c822674a8d8e7d7359fd55067b09fa66"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[odrpack.download]]
    sha256 = "bfc8d903438ff09ecc54d1f512f781e8755ac1f39f9c621f794149203c86c175"
    url = "https://github.com/JuliaBinaryWrappers/odrpack_jll.jl/releases/download/odrpack-v2.0.3+0/odrpack.v2.0.3.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[odrpack]]
arch = "i686"
git-tree-sha1 = "acc3e200a7242ed25e4a7ee756034c6b45f862e6"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[odrpack.download]]
    sha256 = "57afeb8e7d128810e06665cf7845638b97b09bf18edd5a3ee5df3ecfde628619"
    url = "https://github.com/JuliaBinaryWrappers/odrpack_jll.jl/releases/download/odrpack-v2.0.3+0/odrpack.v2.0.3.i686-linux-gnu-libgfortran5.tar.gz"
[[odrpack]]
arch = "i686"
git-tree-sha1 = "ceef95fd09115764c94425d77cb8a79de159a040"
libgfortran_version = "5.0.0"
os = "windows"

    [[odrpack.download]]
    sha256 = "cadd67bf82619a5ae36bbf0a96bbeed6d0f6f6255e2ce0d6754894cf458b12a4"
    url = "https://github.com/JuliaBinaryWrappers/odrpack_jll.jl/releases/download/odrpack-v2.0.3+0/odrpack.v2.0.3.i686-w64-mingw32-libgfortran5.tar.gz"
[[odrpack]]
arch = "powerpc64le"
git-tree-sha1 = "0f5824c314a8cb84cd27df0ef0197994bf9f06cf"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[odrpack.download]]
    sha256 = "f137020a69f4d5df244cc63f26dbe880b397abbc93ef15306686e9f7d9da7fb9"
    url = "https://github.com/JuliaBinaryWrappers/odrpack_jll.jl/releases/download/odrpack-v2.0.3+0/odrpack.v2.0.3.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[odrpack]]
arch = "riscv64"
git-tree-sha1 = "990e5eb26004ba983c429eb129c34c51fb1fa167"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[odrpack.download]]
    sha256 = "2d0fc8ad67d3817c5272e5511cc7f85ba2814140b76075df3973d2998abcb26d"
    url = "https://github.com/JuliaBinaryWrappers/odrpack_jll.jl/releases/download/odrpack-v2.0.3+0/odrpack.v2.0.3.riscv64-linux-gnu-libgfortran5.tar.gz"
[[odrpack]]
arch = "x86_64"
git-tree-sha1 = "263b903837227323e10654d0047f123256fd6a46"
libgfortran_version = "5.0.0"
os = "macos"

    [[odrpack.download]]
    sha256 = "926243c9f3a6803b26fd7e5a5dcb261bdaf235ed1c85e860ae7ee006b93f94bd"
    url = "https://github.com/JuliaBinaryWrappers/odrpack_jll.jl/releases/download/odrpack-v2.0.3+0/odrpack.v2.0.3.x86_64-apple-darwin-libgfortran5.tar.gz"
[[odrpack]]
arch = "x86_64"
git-tree-sha1 = "28cd6a6fac2272cfa8560c236d357db60487d5dd"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[odrpack.download]]
    sha256 = "12c5b0ec32886c8327d560cd996edba8a9ff751c810d4ada36d815c956411ac5"
    url = "https://github.com/JuliaBinaryWrappers/odrpack_jll.jl/releases/download/odrpack-v2.0.3+0/odrpack.v2.0.3.x86_64-linux-gnu-libgfortran5.tar.gz"
[[odrpack]]
arch = "x86_64"
git-tree-sha1 = "d34e42180fb06be72fb785ab377184b2cd0438f2"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[odrpack.download]]
    sha256 = "dca16de649ef2bc9924180059bd82b4600edc7418b080ec16b5a8382bff90faa"
    url = "https://github.com/JuliaBinaryWrappers/odrpack_jll.jl/releases/download/odrpack-v2.0.3+0/odrpack.v2.0.3.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[odrpack]]
arch = "x86_64"
git-tree-sha1 = "30a4096bad126d7522c83c1166e8c74960858cb2"
libgfortran_version = "5.0.0"
os = "windows"

    [[odrpack.download]]
    sha256 = "ca9c782f15df8d0b4743825d50f89ad0fd36ad6df189d18e018adb9ce6a0166e"
    url = "https://github.com/JuliaBinaryWrappers/odrpack_jll.jl/releases/download/odrpack-v2.0.3+0/odrpack.v2.0.3.x86_64-w64-mingw32-libgfortran5.tar.gz"
