[[odrpack]]
arch = "aarch64"
git-tree-sha1 = "5509eafd2b070bef8bc748e729b9f13a51972031"
libgfortran_version = "5.0.0"
os = "macos"

    [[odrpack.download]]
    sha256 = "16fc4ed8f4adddf54a996fdfb6aa5639b39f463d69b2976562328501e99a38f4"
    url = "https://github.com/JuliaBinaryWrappers/odrpack_jll.jl/releases/download/odrpack-v2.1.0+0/odrpack.v2.1.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[odrpack]]
arch = "aarch64"
git-tree-sha1 = "73854a1cf94e7cef7e3e5640faf22d45f70377a1"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[odrpack.download]]
    sha256 = "c4b0654a3f80ecbd40f729951b288e52f3c410d207a919515ac8758dd8bb8709"
    url = "https://github.com/JuliaBinaryWrappers/odrpack_jll.jl/releases/download/odrpack-v2.1.0+0/odrpack.v2.1.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[odrpack]]
arch = "aarch64"
git-tree-sha1 = "a2a1b9a5a6e1a602d51441385e4414cad4129df6"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[odrpack.download]]
    sha256 = "4a8ba6c720a0c3a0a10a5189de5881576adf2cc982b02c6bf3cf7487a26f99fe"
    url = "https://github.com/JuliaBinaryWrappers/odrpack_jll.jl/releases/download/odrpack-v2.1.0+0/odrpack.v2.1.0.aarch64-unknown-freebsd-libgfortran5.tar.gz"
[[odrpack]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "72f162c4bc536dd7a0d2e0df2857740be1513949"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[odrpack.download]]
    sha256 = "6cd60b499d404a8aa361b6f69de311fd1d148eac2f985405479648152d78e6d9"
    url = "https://github.com/JuliaBinaryWrappers/odrpack_jll.jl/releases/download/odrpack-v2.1.0+0/odrpack.v2.1.0.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[odrpack]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "71d41f6686a1edfda851b96ee664164ff6e5f642"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[odrpack.download]]
    sha256 = "fd2a26f0b88c1ebb9ff1d2899e8c0a3a92ced27d824edec33a3939bc91c925bc"
    url = "https://github.com/JuliaBinaryWrappers/odrpack_jll.jl/releases/download/odrpack-v2.1.0+0/odrpack.v2.1.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[odrpack]]
arch = "i686"
git-tree-sha1 = "01ce51e94d1c655a9626f639d5fe7d02c3da6465"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[odrpack.download]]
    sha256 = "003ba1ae6ec1fe63d69e34867928d16e79d82384c3c8ed7641d99f187a2e7683"
    url = "https://github.com/JuliaBinaryWrappers/odrpack_jll.jl/releases/download/odrpack-v2.1.0+0/odrpack.v2.1.0.i686-linux-gnu-libgfortran5.tar.gz"
[[odrpack]]
arch = "i686"
git-tree-sha1 = "5a61b2553382239d527d24e4f4511407bf715c14"
libgfortran_version = "5.0.0"
os = "windows"

    [[odrpack.download]]
    sha256 = "469aab2dd7b48e1bde3858c7530560ee7ae133b97ea9dced0c4011c3e0741478"
    url = "https://github.com/JuliaBinaryWrappers/odrpack_jll.jl/releases/download/odrpack-v2.1.0+0/odrpack.v2.1.0.i686-w64-mingw32-libgfortran5.tar.gz"
[[odrpack]]
arch = "powerpc64le"
git-tree-sha1 = "b57df0ed8dc63e6184143b602d0a9d265c4e45fd"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[odrpack.download]]
    sha256 = "5ebfaab18d999f24f74115a3fe3116cbaa23beac241de52d32759f60973c152f"
    url = "https://github.com/JuliaBinaryWrappers/odrpack_jll.jl/releases/download/odrpack-v2.1.0+0/odrpack.v2.1.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[odrpack]]
arch = "riscv64"
git-tree-sha1 = "ec435e8686d9ffd7e2281d81a254d36a8dd07b4b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[odrpack.download]]
    sha256 = "bf2cee6421c0704f6a833b152b7c2b2e3a7332d0247b89ac031d6f51c595fef4"
    url = "https://github.com/JuliaBinaryWrappers/odrpack_jll.jl/releases/download/odrpack-v2.1.0+0/odrpack.v2.1.0.riscv64-linux-gnu-libgfortran5.tar.gz"
[[odrpack]]
arch = "x86_64"
git-tree-sha1 = "45873c0b0de4b5b78ecd0e2751944cc82b9e251f"
libgfortran_version = "5.0.0"
os = "macos"

    [[odrpack.download]]
    sha256 = "75fe8840044986858c78ec563ec951e14683c0753965fcd4d1590c4b8a201948"
    url = "https://github.com/JuliaBinaryWrappers/odrpack_jll.jl/releases/download/odrpack-v2.1.0+0/odrpack.v2.1.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[odrpack]]
arch = "x86_64"
git-tree-sha1 = "57ca081eeae1adf81239e61091f28b02734ffd54"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[odrpack.download]]
    sha256 = "0b044c1711fe7067516d8b5f80f2ece493166e67090d218cc3eb2357cc725c15"
    url = "https://github.com/JuliaBinaryWrappers/odrpack_jll.jl/releases/download/odrpack-v2.1.0+0/odrpack.v2.1.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[odrpack]]
arch = "x86_64"
git-tree-sha1 = "3d085f3dca45ce41c443b9b6b26a810099c8d1f8"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[odrpack.download]]
    sha256 = "039e6cc74cd1ccb01fd785fe9d035968d3edbbf0bb4b5f61a49e08c65fb8db49"
    url = "https://github.com/JuliaBinaryWrappers/odrpack_jll.jl/releases/download/odrpack-v2.1.0+0/odrpack.v2.1.0.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[odrpack]]
arch = "x86_64"
git-tree-sha1 = "90ed3a18ef5b6e1563fddbf55a5b4109359d661b"
libgfortran_version = "5.0.0"
os = "windows"

    [[odrpack.download]]
    sha256 = "90ea1ecc473593b69c9b7382f8c0fff9b3042be1c312cc378c13fd6eadb43d00"
    url = "https://github.com/JuliaBinaryWrappers/odrpack_jll.jl/releases/download/odrpack-v2.1.0+0/odrpack.v2.1.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
