# Autogenerated wrapper script for odrpack_jll for aarch64-apple-darwin-libgfortran5
export libodrpack95

using CompilerSupportLibraries_jll
using OpenBLAS32_jll
JLLWrappers.@generate_wrapper_header("odrpack")
JLLWrappers.@declare_library_product(libodrpack95, "@rpath/libodrpack95.dylib")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, OpenBLAS32_jll)
    JLLWrappers.@init_library_product(
        libodrpack95,
        "lib/libodrpack95.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
