# Autogenerated wrapper script for odrpack_jll for i686-linux-musl-libgfortran5
export libodrpack95

using CompilerSupportLibraries_jll
using OpenBLAS32_jll
JLLWrappers.@generate_wrapper_header("odrpack")
JLLWrappers.@declare_library_product(libodrpack95, "libodrpack95.so")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, OpenBLAS32_jll)
    JLLWrappers.@init_library_product(
        libodrpack95,
        "lib/libodrpack95.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
